packages:
  - "packages/*"

overrides:
  "@earendil-works/pi-ai": "$@earendil-works/pi-coding-agent"
  "@earendil-works/pi-tui": "$@earendil-works/pi-coding-agent"
  "@earendil-works/pi-agent-core": "$@earendil-works/pi-coding-agent"

allowBuilds:
  '@google/genai': false
  esbuild: true
  protobufjs: true
